// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, title, created_at) 
VALUES ($1, $2, $3)
RETURNING id, title, created_at
`

type CreateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.ID, arg.Title, arg.CreatedAt)
	var i Category
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, title, created_at FROM categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, title, created_at FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryById(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, title, created_at FROM categories
WHERE title = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, title string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, title)
	var i Category
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}
