// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: details.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDetail = `-- name: CreateDetail :one
INSERT INTO details (id, name, width, length, amount, product_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, width, length, amount, product_id, created_at, updated_at
`

type CreateDetailParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Width     int32     `json:"width"`
	Length    int32     `json:"length"`
	Amount    int32     `json:"amount"`
	ProductID uuid.UUID `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateDetail(ctx context.Context, arg CreateDetailParams) (Detail, error) {
	row := q.db.QueryRowContext(ctx, createDetail,
		arg.ID,
		arg.Name,
		arg.Width,
		arg.Length,
		arg.Amount,
		arg.ProductID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Detail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Length,
		&i.Amount,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDetailById = `-- name: DeleteDetailById :exec
DELETE FROM details WHERE id = $1
`

func (q *Queries) DeleteDetailById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDetailById, id)
	return err
}

const getAllDetails = `-- name: GetAllDetails :many
SELECT id, name, width, length, amount, product_id, created_at, updated_at FROM details
`

func (q *Queries) GetAllDetails(ctx context.Context) ([]Detail, error) {
	rows, err := q.db.QueryContext(ctx, getAllDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Detail
	for rows.Next() {
		var i Detail
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Length,
			&i.Amount,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDetailById = `-- name: GetDetailById :one
SELECT id, name, width, length, amount, product_id, created_at, updated_at FROM details WHERE id = $1
`

func (q *Queries) GetDetailById(ctx context.Context, id uuid.UUID) (Detail, error) {
	row := q.db.QueryRowContext(ctx, getDetailById, id)
	var i Detail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Length,
		&i.Amount,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDetailById = `-- name: UpdateDetailById :one
UPDATE details
SET name = $2, width = $3, length = $4, amount = $5, product_id = $6, updated_at = $7
WHERE id = $1
RETURNING id, name, width, length, amount, product_id, created_at, updated_at
`

type UpdateDetailByIdParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Width     int32     `json:"width"`
	Length    int32     `json:"length"`
	Amount    int32     `json:"amount"`
	ProductID uuid.UUID `json:"product_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateDetailById(ctx context.Context, arg UpdateDetailByIdParams) (Detail, error) {
	row := q.db.QueryRowContext(ctx, updateDetailById,
		arg.ID,
		arg.Name,
		arg.Width,
		arg.Length,
		arg.Amount,
		arg.ProductID,
		arg.UpdatedAt,
	)
	var i Detail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Length,
		&i.Amount,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
