// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, title, excel_url, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, excel_url, user_id, created_at, updated_at
`

type CreateOrderParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	ExcelUrl  string    `json:"excel_url"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.Title,
		arg.ExcelUrl,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ExcelUrl,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderById = `-- name: DeleteOrderById :exec
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrderById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderById, id)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, title, excel_url, user_id, created_at, updated_at FROM orders
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ExcelUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, title, excel_url, user_id, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ExcelUrl,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderById = `-- name: UpdateOrderById :one
UPDATE orders
SET title = $2, excel_url = $3, updated_at = $4
WHERE id = $1
RETURNING id, title, excel_url, user_id, created_at, updated_at
`

type UpdateOrderByIdParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	ExcelUrl  string    `json:"excel_url"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrderById(ctx context.Context, arg UpdateOrderByIdParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderById,
		arg.ID,
		arg.Title,
		arg.ExcelUrl,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ExcelUrl,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
