// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, quantity, order_id, product_id, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, quantity, order_id, product_id, created_at
`

type CreateOrderItemParams struct {
	ID        uuid.UUID `json:"id"`
	Quantity  int32     `json:"quantity"`
	OrderID   uuid.UUID `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.ID,
		arg.Quantity,
		arg.OrderID,
		arg.ProductID,
		arg.CreatedAt,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.OrderID,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const getAllOrderItems = `-- name: GetAllOrderItems :many
SELECT id, quantity, order_id, product_id, created_at FROM order_items
`

func (q *Queries) GetAllOrderItems(ctx context.Context) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrderItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.OrderID,
			&i.ProductID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemById = `-- name: GetOrderItemById :one
SELECT id, quantity, order_id, product_id, created_at FROM order_items WHERE id = $1
`

func (q *Queries) GetOrderItemById(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemById, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.OrderID,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}
