// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, description, image_url, created_at, updated_at, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, image_url, created_at, updated_at, category_id
`

type CreateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	CategoryID  uuid.UUID `json:"category_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const deleteProductById = `-- name: DeleteProductById :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProductById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductById, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, description, image_url, created_at, updated_at, category_id FROM products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT id, name, description, image_url, created_at, updated_at, category_id FROM products WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT products.id, products.name, products.description, products.image_url, products.created_at, products.updated_at, products.category_id, categories.title AS category 
FROM products
JOIN categories ON products.category_id = categories.id
WHERE categories.id = $1
`

type GetProductsByCategoryRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	CategoryID  uuid.UUID `json:"category_id"`
	Category    string    `json:"category"`
}

func (q *Queries) GetProductsByCategory(ctx context.Context, id uuid.UUID) ([]GetProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByCategory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryRow
	for rows.Next() {
		var i GetProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByCategoryName = `-- name: GetProductsByCategoryName :many
SELECT products.id, products.name, products.description, products.image_url, products.created_at, products.updated_at, products.category_id, categories.title AS category 
FROM products
JOIN categories ON products.category_id = categories.id
WHERE categories.title = $1
`

type GetProductsByCategoryNameRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	CategoryID  uuid.UUID `json:"category_id"`
	Category    string    `json:"category"`
}

func (q *Queries) GetProductsByCategoryName(ctx context.Context, title string) ([]GetProductsByCategoryNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByCategoryName, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryNameRow
	for rows.Next() {
		var i GetProductsByCategoryNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductById = `-- name: UpdateProductById :one
UPDATE products
SET name = $2, description = $3, image_url = $4, updated_at = $5
WHERE id = $1
RETURNING id, name, description, image_url, created_at, updated_at, category_id
`

type UpdateProductByIdParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProductById(ctx context.Context, arg UpdateProductByIdParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductById,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}
